### ISSUE TITLE
Lost Settings on Unexpected Shutdowns

### ISSUE THREAD

**Issue by jaruba** [nathanbuchar/electron-settings#110]
I have an issue with the current PC where it just restarts randomly sometimes. Every time it happens, if the app that uses this module is running, the entirety of the db from `electron-settings` gets completely wiped out.

Is my assumption that this cannot be corrected and I should look for a "more persistent" db solution correct?

**Comment by nathanbuchar** [comment]
If your computer restarts in the middle of a write, then the Electron Settings file may become corrupted. If when Electron Settings tries to read the settings file and it's corrupted, it has no other choice than to abort and start from scratch. 

In theory I could reimplement atomic saving to help mitigate this kind of behavior. I used to have it but I guess in a rewrite I must have missed it. I'll try to find some time this weekend :)

**Comment by jaruba** [comment]
> If your computer restarts in the middle of a write

Well this is interesting, it doesn't really seem like an "if" scenario, with an experience of tens of random restarts, it wiped out the data in 100% of the cases.

> In theory I could reimplement atomic saving to help mitigate this kind of behavior.

I can easily test that with my current scenario.

**Comment by jaruba** [comment]
You were right, I implemented atomic save in `electron-settings` with:
- these changes in `jsonfile`: https://github.com/jprichardson/node-jsonfile/pull/108/files
- these changes in `electron-settings`: https://github.com/jaruba/electron-settings/commit/7b7b0f2b0b99d762f3193ec08bf3de04cf530835

And it fixed the issue. If the PR goes through at `jsonfile` and you have no issues with the changes made to `electron-settings`, then I'll make a PR for `electron-settings` too.

**Comment by jaruba** [comment]
They dropped the PR: https://github.com/jprichardson/node-jsonfile/pull/108

It doesn't surprise me.. i'll make a new project `atomic-jsonfile` as per their suggestion, you're welcome to use if for this purpose if you wish to.

I'll share the link as soon as I have one.

**Comment by nathanbuchar** [comment]
Already working on a v4 at the moment which will use [`write-file-atomic`](https://www.npmjs.com/package/write-file-atomic). Stay tuned :)

**Comment by jaruba** [comment]
Even better. I'm used to project authors disappearing silently into the night, so i usually take shit into my own hands..

**Comment by marcoancona** [comment]
Not sure if it is related but I also experience sudden (and apparently random) loss of all settings.
Initially we though this was because we were using the library from both the main and renderer process, but when we fixed that, although less frequently, we got reports from users that the problem persists.

**Comment by nathanbuchar** [comment]
Currently working on a much more robust version w/ fault detection atomic saving :) This should eliminate the issue of collisions due to using electron settings in multiple processes as well as unexpected data loss

**Comment by jaruba** [comment]
@nathanbuchar

When i tested with atomic saving, it wasn't perfect.

As in, if i had my app running for 3 days straight, then got an unexpected shutdown, it wouldn't delete the entirety of the settings like it used to, but it would remove all the data since the last app start (in this example's case, 3 days of unsaved data)

**Comment by jaruba** [comment]
Don't get me wrong, it's still much better, but far from a perfect scenario too. At least in my case where my app runs on start-up.

**Comment by nathanbuchar** [comment]
> but it would remove all the data since the last app start (in this example's case, 3 days of unsaved data)

In this case, do you think it actually have something to do with Electron and your OS? Perhaps try another settings manager, like electron-json-storage or electron-config and see if you see similar issues

**Comment by jaruba** [comment]
My OS is Windows 10, not sure if this is OS specific, it kind of feels like electron-settings is keeping all changes in memory and only saving to file on app close.

If my presumption is true though, it would be awesome if we could also save manually. As I could make it save on a 60 min interval.

**Comment by nathanbuchar** [comment]
@jaruba I definitely did not write in a hook that would do that, but that was my thinking as well.

And unfortunately it's not ~possible~ feasible to keep a local copy of the settings and then save the settings every so often, unless run Electron Settings within a single thread (e.g., only in the main process, or only in a single renderer process). Since processes don't share memory, you would end up with multiple sources of truth.

In fact, v1 of Electron Settings did this, as it was adapted from Atom's internal config manager where users actually read to and from a local JSON object, and any changes that were made would run a save procedure in the background. It's super efficient, but it only works in a single process (in Atom's case, the main process). I'd love to keep this kind of system as it's super clean (I actually recently rewrote it this way again for fun), but the unfortunate truth is that asking users to only run Electron Settings in a single process is a big ask, and many users might miss the caveat then I end up with a bunch of GitHub issues.

All that said, Electron Settings and other settings managers read and write directly to the file system on every method call, because it's the only way to guarantee a single source of truth (and frankly it's a lot easier than having to manage a save scheduler).

Also, you're welcome to give Electron Settings v4 a shot: https://github.com/nathanbuchar/electron-settings/tree/v4, note however that there are quite a few significant/breaking changes. I don't have any documentation written up for it, but I'm sure you could figure it out by looking at the source code and the tests. I'm nothing if not verbose in my commenting

**Comment by marcoancona** [comment]
Looking forward to try v4. Is the release coming soon? I was looking at the changes of this version and one change in particular popped out. Why the tool is not a singleton anymore but you need to use `new ElectronSettings()` everytime?

**Comment by nathanbuchar** [comment]
@marcoancona,

Yeah there were a couple reasons for this. For one, it's a lot easier to specify the Electron Settings options (of which there are more). Things like the encryption key, encryption algorithm, file name, save directory, whether to disable atomic saving or not, whether to prettify that output or not, etc. These kind of options would be a pain to specify on every `set` call, so it just made sense to me to turn it into a class instead of a singleton. I've also had requests from time to time from people who want to have more than one settings file.

I suppose I could have created something like an `init` method which would allow you to specify the options for the singleton, but that kind of just feels like a hacky way to use a singleton as a class. Plus, by using `init()`, those settings would only be stored in a single process. So if you call `init()` in the main process but use `set()` in a renderer processes, those settings won't be honored because Electron processes don't share memory. Using a class sort of guarantees that if you access the instance of that class, it has the same settings as an instance in a different process

I do rather like the simplicity of a singleton, but it's very limiting. Electron Settings stands alone among the other settings managers as being – in general – a bit more powerful and customizable (which I admit is not my usual focus)

Happy to hear counter arguments to this though. It's one of the reasons I haven't pushed v4 to `latest`

**Comment by marcoancona** [comment]
> I'm not sure what you mean exactly. One would only need to call cont settings = new ElectronSettings() once in the entire application, and thereafter just use the settings instance to make set() etc calls.

Wait, how can I pass this instance around between different modules?
Right now I have a `const settings = require('electron-settings')` in every .js file where I need to access those settings. I can create an instance of `ElectronSettings` in each module, but seems not to be the best way to go.
Otherwise I would have to create my own settings module wrapper, where I instantiate ElectronSettings once (as a singleton) and use that instance from other places.
Also, when you say "once in the entire application", do you mean once in the main and once in the renderer process? (If I understand correctly, with the new version accessing from multiple processes is possible, isn't it?)

**Comment by marcoancona** [comment]
Oh, btw, I might have understood why I still loose settings every now and then.

I am using `const settings = require('electron-settings')` everywhere in the main process. This is fine, I will have a single instance of the Settings class anyway because of [caching](https://medium.com/@lazlojuly/are-node-js-modules-singletons-764ae97519af).
Now the problem is that in the renderer process, I have `const settings = require('electron').remote.require('electron-settings')` everywhere and this does *not* use the same instance as I was expecting! Not totally sure why though!

**Comment by marcoancona** [comment]
One more feedback for v4. Instead of `set()` and `setSync()`, why not calling them `setAsync()` and `set()`. This would make it back-compatible, wouldn't it?

**Comment by nathanbuchar** [comment]
@marcoancona It would be more inline with older versions of Electron Settings, you're right. However, this is a new major version, so backwards compatibility is not an issue, but you're right it would be different and it would outdate any tutorials that use electron settings.

I considered using sync by default and having an `xAsync` alternative, but that's just not the standard practice for Node.js. I think I'd rather follow the standard of async by default with a `xSync` option, rather than break convention

**Comment by ashleydavis** [comment]
@nathanbuchar what's the status of this issue? 

I'm getting the problem as well and it seem to lose my settings much more frequently since I just added support for multiple windows to my Electron application.

**Comment by jaruba** [comment]
I had to overengineer this in my app.. thing is, in my case, it's a torrent client, so it updates the json file frequently (to update download / uploaded of items, etc.)

I came to the conclusion that the frequent updating (writing to file) increased the chances (although it seems to always happen) to write exactly when the PC would crash or shut down unexpectedly, resulting in a total wipe. Atomic save didn't help at all.

Now i make a backup of the json file every hour, and replace the settings with the backup if it got completely wiped again, as for the user settings, i moved those to a different json file, as user settings are more important, and because they are changed rarely, that file never gets wiped.

This is obviously not a solution, just stating my experience with this in case it helps others too.

**Comment by jaruba** [comment]
Also, to note, I've tested many other json db modules, they all have the exact same issue.

**Comment by ashleydavis** [comment]
I've actually created my own simple settings code now. This problem became unavoidable. Turned out to be simple to replace for my own needs.

It uses Electron IPC to transfer settings between main process and renderer process. In my system only the main process is allowed to write the JSON file. That solves the issue of main and renderer fighting to control the file. So a renderer can change a setting which sends a message to the main process. The main process broadcasts the setting change to all renderers. Then it does a debounced write of the JSON file, so as soon as settings stop being changed for 1 second it writes the file.

If anyone is interested in my solution I can put the code on GitHub, just let me know.

**Comment by nathanbuchar** [comment]
@ashleydavis this is a great solution. As for where I am with "v4", I look at the code from time to time and make changes but I haven't found myself satisfied enough to publish it, but I think @ashleydavis' solution might be just the key I'm looking for. I'm not going to commit to a timeline, but I am aware that this is an ongoing issue and I would like to eventually get a seamless fix published

**Comment by ashleydavis** [comment]
Good luck @nathanbuchar, this is a good library and I hope you get it sorted out.

**Comment by nathanbuchar** [comment]
@ashleydavis could you share your cod eon GitHub? Been a while since I've done Electron work, a starting point for how you handled the IPC would be greatly appreciated :)

**Comment by topstreamapp** [comment]
@nathanbuchar this issue makes my application users really unhappy. I'm recieveing messages about "lost settings" every week.
Already implemented backup and restore buttons, but it makes no sense, cause too many people are  losing their settings.

**Comment by semireg** [comment]
Will v4 ever be released? After what seemed like no issues for a few releases I just started getting `Unexpected end of JSON input` from Windows users.

**Comment by nathanbuchar** [comment]
Closing this as it pertains to an older version of Electron Settings. A new major release (v4) of Electron Settings was just released!

**Comment by appurist** [comment]
> Also, you're welcome to give Electron Settings v4 a shot: https://github.com/nathanbuchar/electron-settings/tree/v4, note however that there are quite a few significant/breaking changes. I don't have any documentation written up for it yet, but I'm sure you could figure it out by looking at the source code and the tests. I'm nothing if not verbose in my commenting

I've upgraded to electron-settings 4.x and indeed plenty of breaking changes, none of which seem documented anywhere in the  2.5 years since this comment. I've been googling and _this Issue_ is the closest thing I've found to any form of confirmation or documentation of the breaking changes in 4.x. There aren't even any release notes with the 4.0.0 upgrade (or _any_ electron-settings releases). No support at all for existing users trying to make their existing code function after these changes.

Depending on how your code is structured, for others looking for answers on this, the symptom is sometimes "Error: An object could not be cloned." (or a warning about unresolved promises). See [https://github.com/electron/electron/issues/23722](https://github.com/electron/electron/issues/23722) for more.

Since there are major breaking changes, I would have expected at list a short table of old functions and parameters mapped to new functions and parameters. It also looks like some functions may have just been outright removed (is the `.delete` method just _gone_ now)?  This has cost me the better part of a day, because there is no documentation for the major upgrade and breaking changes.

I initially just rolled back to 3.x for now, but then eventually attempted to complete an upgrade again. I am abandoning that now due to a lack of migration documentation, and going to proceed by eliminating my use of electron-settings going forward.

I already had a scheme similar to the design @ashleydavis came up with (remote IPC to coordinate a single instance of settings data). I'm going to do away with the settings entirely and just have the main process code ask the renderer for localStorage data. This means it won't be available until after the mainWindow is available, but I can adjust the window after it is opened, before a mainWindow.show() and achieve the same results without this added dependency.

I'm very disappointed by the cavalier "it's a x.0 upgrade anyway" attitude above, and while that may be true, without documenting the migration needed to go from 3.x to 4.x, it puts a large unnecessary burden on the developer who previously adopted your library.
